epg:
  cache-dir: /var/lib/mirakc/epg

server:
  addrs:
    - !http '0.0.0.0:40772'

channels:
  - name: EX
    type: GR
    channel: '24'
  - name: NTV
    type: GR
    channel: '25'
  - name: ETV
    type: GR
    channel: '26'
  - name: NHK
    type: GR
    channel: '27'
  - name: BS1
    type: BS
    channel: BS15_0
  - name: BSP
    type: BS
    channel: BS03_1
  - name: BS-NTV
    type: BS
    channel: BS13_0
  - name: BS-EX
    type: BS
    channel: BS01_0

tuners:
  - name: gr1
    types: [GR]
    command: >-
      curl -sG http://upstream:40772/api/channels/GR/{{{channel}}}/stream
  - name: gr2
    types: [GR]
    command: >-
      curl -sG http://upstream:40772/api/channels/GR/{{{channel}}}/stream
  - name: gr3
    types: [GR]
    command: >-
      curl -sG http://upstream:40772/api/channels/GR/{{{channel}}}/stream
  - name: gr4
    types: [GR]
    command: >-
      curl -sG http://upstream:40772/api/channels/GR/{{{channel}}}/stream
  - name: bs1
    types: [BS]
    command: >-
      curl -sG http://upstream:40772/api/channels/BS/{{{channel}}}/stream
  - name: bs2
    types: [BS]
    command: >-
      curl -sG http://upstream:40772/api/channels/BS/{{{channel}}}/stream
  - name: bs3
    types: [BS]
    command: >-
      curl -sG http://upstream:40772/api/channels/BS/{{{channel}}}/stream
  - name: bs4
    types: [BS]
    command: >-
      curl -sG http://upstream:40772/api/channels/BS/{{{channel}}}/stream

filters:
  decode-filter:
    command: cat
