- name: EX
  type: GR
  channel: '24'
- name: NTV
  type: GR
  channel: '25'
- name: ETV
  type: GR
  channel: '26'
- name: NHK
  type: GR
  channel: '27'
- name: BS1
  type: BS
  channel: BS15_0
- name: BSP
  type: BS
  channel: BS03_1
- name: BS-NTV
  type: BS
  channel: BS13_0
- name: BS-EX
  type: BS
  channel: BS01_0
