version: '3'

x-environment: &default-environment
  TZ: $TZ

services:
  mirakurun:
    container_name: mirakurun
    image: chinachu/mirakurun
    command: 'sh /app/run.sh'
    init: true
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    ports:
      - '40772:40772'
    volumes:
      - mirakurun-data:/app-data
      - ./run.sh:/app/run.sh
      - ./config:/app-config:ro
    environment:
      <<: *default-environment
    extra_hosts:
      - "upstream:$UPSTREAM_IPADDR"

  prometheus-node-exporter:
    container_name: prometheus-node-exporter
    image: prom/node-exporter
    command: --path.rootfs=/host
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    environment:
      <<: *default-environment
    logging:
      driver: none

volumes:
  mirakurun-data:
    name: mirakurun_data
    driver: local
