version: '3'

x-environment: &default-environment
  TZ: $TZ

services:
  mirakc:
    container_name: mirakc-alpine
    image: mirakc/mirakc:main-alpine
    init: true
    restart: unless-stopped
    ports:
      - '40772:40772'
    volumes:
      - mirakc-epg:/var/lib/mirakc/epg
      - ./config.yml:/etc/mirakc/config.yml:ro
    environment:
      <<: *default-environment
      RUST_LOG: 'info,mirakc=debug'
      RUST_LOG_STYLE: never
      MIRAKC_DEBUG_CHILD_PROCESS: 1
      MIRAKC_ARIB_LOG: 'info'
      MIRAKC_ARIB_LOG_NO_TIMESTAMP: 1
      MALLOC_ARENA_MAX: 2
    extra_hosts:
      - "upstream:$UPSTREAM_IPADDR"

  prometheus-node-exporter:
    container_name: prometheus-node-exporter
    image: prom/node-exporter
    command: --path.rootfs=/host
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    environment:
      <<: *default-environment
    logging:
      driver: none

volumes:
  mirakc-epg:
    name: mirakc_alpine_epg
    driver: local
