global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
      - targets:
          - target:9100
    relabel_configs:
      - source_labels: [__address__]
        target_label: name
        regex: '(.*):.*'
        replacement: ${1}
